# Generated by Django 4.1.3 on 2022-11-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanchonete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='produto',
        ),
        migrations.AlterField(
            model_name='prato',
            name='ingredientes',
            field=models.ManyToManyField(null=True, to='lanchonete.ingrediente'),
        ),
    ]
