# Generated by Django 4.1.3 on 2022-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanchonete', '0002_ingrediente_delete_produto_alter_prato_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
