# Generated by Django 4.1.3 on 2022-11-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanchonete', '0009_alter_prato_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='prato_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='prato',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='prato',
            name='ingredientes',
        ),
        migrations.DeleteModel(
            name='categoria',
        ),
        migrations.DeleteModel(
            name='ingrediente',
        ),
        migrations.DeleteModel(
            name='pedido',
        ),
        migrations.DeleteModel(
            name='prato',
        ),
    ]
