# Generated by Django 4.1.3 on 2022-11-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('lanchonete', '0010_remove_pedido_prato_pedido_remove_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('preco', models.FloatField(null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanchonete.categoria')),
                ('ingredientes', models.ManyToManyField(null=True, to='lanchonete.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField()),
                ('valor_pedido', models.FloatField()),
                ('prato_pedido', models.ManyToManyField(null=True, to='lanchonete.prato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario')),
            ],
        ),
    ]
