# Generated by Django 4.1.3 on 2022-11-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanchonete', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='img',
            field=models.ImageField(null=True, upload_to='lanchonete/media'),
        ),
    ]
